# Generated by Django 5.1.5 on 2025-01-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_shorten", models.DateField(auto_now=True)),
                ("url_original", models.CharField(max_length=256)),
                ("url_shorted", models.CharField(max_length=256)),
                ("number_visits", models.IntegerField()),
            ],
        ),
    ]
